Test 27

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,7 +20,26 @@ jobs:
         - name:                  Start sJob
           run:                   failJob=false
         - name:                  lint_style
-          run:                   ./phpcs.sh
+          run:                   failTest=false
+          echo "--------------------------------------"
+          echo "Checking for PHP styling (PSR-12) issues"
+          echo "--------------------------------------"
+          composer global require "squizlabs/php_codesniffer=3.*" || failTest=true
+          $HOME/.config/composer/vendor/bin/phpcs -p -n --extensions=php,inc --report-width=120 --standard=ci/phpcs.xml --report=full . || failTest=true
+          # todo clean up method visibility and other refactors in src/
+          # $HOME/.config/composer/vendor/bin/phpcs -p -n --extensions=php,inc --report-width=120 --standard=ci/phpcs_src.xml --report=full src/ || failTest=true
+
+          if $failTest; then
+          failJob=true
+          mes="FAILED"
+          else
+          mes="PASSED"
+          fi
+          echo "-----------------------------------------------"
+          jobTest="${mes} - Checking for PHP styling (PSR-12) issues"
+          jobTests+="${jobTest}\n"
+          echo "${jobTest}"
+          echo "-----------------------------------------------"
         - name:                  job_summary_prep
           run:                   ./job_summary_prep.sh
   themestyle:
