Smoke Test 9

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,112 +1,8 @@
 name: Build
-.steps:
-
-  - &build_test_e2e |
-      failTest=false
-      echo "-------------"
-      echo "Run E2e Tests"
-      echo "-------------"
-      docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c "${CHROMIUM_INSTALL}; export PANTHER_NO_SANDBOX=1; cd ${OPENEMR_DIR}; php ${OPENEMR_DIR}/vendor/bin/phpunit --testsuite e2e --testdox" || failTest=true
-      if $failTest; then
-        failJob=true
-        mes="FAILED"
-      else
-        mes="PASSED"
-      fi
-      echo "----------------------"
-      jobTest="${mes} - Run E2e Tests"
-      jobTests+="${jobTest}\n"
-      echo "${jobTest}"
-      echo "----------------------"
-  - &build_test_api |
-      failTest=false
-      echo "-------------"
-      echo "Run Api Tests"
-      echo "-------------"
-      docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c "cd ${OPENEMR_DIR}; php ${OPENEMR_DIR}/vendor/bin/phpunit --testsuite api --testdox" || failTest=true
-      if $failTest; then
-        failJob=true
-        mes="FAILED"
-      else
-        mes="PASSED"
-      fi
-      echo "----------------------"
-      jobTest="${mes} - Run Api Tests"
-      jobTests+="${jobTest}\n"
-      echo "${jobTest}"
-      echo "----------------------"
-  - &build_test_fixtures |
-      failTest=false
-      echo "-------------"
-      echo "Run Fixture Tests"
-      echo "-------------"
-      docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c "cd ${OPENEMR_DIR}; php ${OPENEMR_DIR}/vendor/bin/phpunit --testsuite fixtures --testdox" || failTest=true
-      if $failTest; then
-        failJob=true
-        mes="FAILED"
-      else
-        mes="PASSED"
-      fi
-      echo "----------------------"
-      jobTest="${mes} - Run Fixture Tests"
-      jobTests+="${jobTest}\n"
-      echo "${jobTest}"
-      echo "----------------------"
-  - &build_test_services |
-      failTest=false
-      echo "-------------"
-      echo "Run Service Tests"
-      echo "-------------"
-      docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c "cd ${OPENEMR_DIR}; php ${OPENEMR_DIR}/vendor/bin/phpunit --testsuite services --testdox" || failTest=true
-      if $failTest; then
-        failJob=true
-        mes="FAILED"
-      else
-        mes="PASSED"
-      fi
-      echo "----------------------"
-      jobTest="${mes} - Run Service Tests"
-      jobTests+="${jobTest}\n"
-      echo "${jobTest}"
-      echo "----------------------"
-  - &build_test_validators |
-      failTest=false
-      echo "-------------"
-      echo "Run Validator Tests"
-      echo "-------------"
-      docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c "cd ${OPENEMR_DIR}; php ${OPENEMR_DIR}/vendor/bin/phpunit --testsuite validators --testdox" || failTest=true
-      if $failTest; then
-        failJob=true
-        mes="FAILED"
-      else
-        mes="PASSED"
-      fi
-      echo "----------------------"
-      jobTest="${mes} - Run Validator Tests"
-      jobTests+="${jobTest}\n"
-      echo "${jobTest}"
-      echo "----------------------"
-  - &build_test_controllers |
-      failTest=false
-      echo "-------------"
-      echo "Run Controller Tests"
-      echo "-------------"
-      docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c "cd ${OPENEMR_DIR}; php ${OPENEMR_DIR}/vendor/bin/phpunit --testsuite controllers --testdox" || failTest=true
-      if $failTest; then
-        failJob=true
-        mes="FAILED"
-      else
-        mes="PASSED"
-      fi
-      echo "----------------------"
-      jobTest="${mes} - Run Controller Tests"
-      jobTests+="${jobTest}\n"
-      echo "${jobTest}"
-      echo "----------------------"
-before_install:
-  - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``
-before_script:
-  - echo 'error_reporting = "E_ALL & ~E_NOTICE & ~E_STRICT"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
+#efore_install:
+#  - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``
+#before_script:
+#  - echo 'error_reporting = "E_ALL & ~E_NOTICE & ~E_STRICT"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 jobs:
   build:
     - name: Psr12 style
@@ -448,12 +344,18 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_api
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_api
+          run: build_test_api.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -576,12 +478,18 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_api
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_api
+          run: build_test_api.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -704,12 +612,18 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_api
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_api
+          run: build_test_api.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -832,12 +746,18 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_api
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_api
+          run: build_test_api.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -960,12 +880,18 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_api
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_api
+          run: build_test_api.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -1088,12 +1014,18 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_api
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_api
+          run: build_test_api.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -1216,12 +1148,18 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_api
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_api
+          run: build_test_api.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -1344,12 +1282,18 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_api
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_api
+          run: build_test_api.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -1472,11 +1416,16 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
         - name: job_summary_prep
           run: |
             if $failJob; then
@@ -1599,14 +1548,31 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
-        - *job_summary_prep
-        - echo -e "${jobSummary}"
-        - if $failJob; then exit 1; fi
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
+        - name: job_summary_prep
+          run: |
+            if $failJob; then
+            mes="FAILED"
+            else
+            mes="PASSED"
+            fi
+            jobSummary="--------------------------------------------\n"
+            jobSummary+="--------------------------------------------\n"
+            jobSummary+="${mes} - JOB SUMMARY\n"
+            jobSummary+="--------------------------------------------\n"
+            jobSummary+="${jobTests}"
+            jobSummary+="--------------------------------------------"
+            echo -e "${jobSummary}"
+            if $failJob; then exit 1; fi
     - name: Build and test - PHP 7.4 - Nginx - MariaDB 10.4
       uses: shivammathur/setup-php@v2
       with:
@@ -1714,14 +1680,31 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
-        - *job_summary_prep
-        - echo -e "${jobSummary}"
-        - if $failJob; then exit 1; fi
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
+        - name: job_summary_prep
+          run: |
+            if $failJob; then
+            mes="FAILED"
+            else
+            mes="PASSED"
+            fi
+            jobSummary="--------------------------------------------\n"
+            jobSummary+="--------------------------------------------\n"
+            jobSummary+="${mes} - JOB SUMMARY\n"
+            jobSummary+="--------------------------------------------\n"
+            jobSummary+="${jobTests}"
+            jobSummary+="--------------------------------------------"
+            echo -e "${jobSummary}"
+            if $failJob; then exit 1; fi
     - name: Build and test - PHP 8.0 - Nginx - MariaDB 10.4
       uses: shivammathur/setup-php@v2
       with:
@@ -1829,14 +1812,31 @@ jobs:
             echo "-------------------------------------------------------------------------------------------------------"
         - name: build_test_unit
           run: build_test_unit.sh
-        - *build_test_e2e
-        - *build_test_fixtures
-        - *build_test_services
-        - *build_test_validators
-        - *build_test_controllers
-        - *job_summary_prep
-        - echo -e "${jobSummary}"
-        - if $failJob; then exit 1; fi
+        - name: build_test_e2e
+          run: build_test_e2e.sh
+        - name: build_test_fixtures
+          run: build_test_fixtures.sh
+        - name: build_test_services
+          run: build_test_services.sh
+        - name: build_test_validators
+          run: build_test_validators.sh
+        - name: build_test_controllers
+          run: build_test_controllers.sh
+        - name: job_summary_prep
+          run: |
+            if $failJob; then
+            mes="FAILED"
+            else
+            mes="PASSED"
+            fi
+            jobSummary="--------------------------------------------\n"
+            jobSummary+="--------------------------------------------\n"
+            jobSummary+="${mes} - JOB SUMMARY\n"
+            jobSummary+="--------------------------------------------\n"
+            jobSummary+="${jobTests}"
+            jobSummary+="--------------------------------------------"
+            echo -e "${jobSummary}"
+            if $failJob; then exit 1; fi
   allow_failures:
     - name: Build and test - PHP 7.3 - Apache - MariaDB 10.5
     - name: Syntax - PHP 8.0
